name: crypto_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: 13.0.1 
  provider: 6.1.2
  fuzzywuzzy: 1.1.6
  expandable_text: 2.3.0
  flutter_svg: 2.0.10+1     
  http: ^1.2.1
  syncfusion_flutter_charts: ^25.2.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
